# Exploratory Data Analysis and Insights on CO₂ Emissions of Canadian Vehicles Using Pandas

### Beginner-Level Pandas Practice Notebook

This notebook is designed for candidates who are currently learning the basics of **Pandas**.  
The exercises focus on simple data inspection, selection, filtering, missing-value checking, string operations, and basic DataFrame manipulation.

## About the Dataset

The **CO2 Emissions_Canada.csv** dataset contains information about different vehicle models and their fuel consumption and CO₂ emission values.

The dataset contains:

- **7,385 rows**
- **12 columns**
- **No missing values were found during the initial dataset review**

### Columns in the Dataset

| Column | Description |
|---|---|
| `Make` | Vehicle manufacturer / brand |
| `Model` | Vehicle model |
| `Vehicle Class` | Category or class of the vehicle |
| `Engine Size(L)` | Engine size in litres |
| `Cylinders` | Number of engine cylinders |
| `Transmission` | Transmission category/code |
| `Fuel Type` | Fuel type category/code |
| `Fuel Consumption City (L/100 km)` | Fuel consumption in city driving |
| `Fuel Consumption Hwy (L/100 km)` | Fuel consumption on highway driving |
| `Fuel Consumption Comb (L/100 km)` | Combined fuel consumption |
| `Fuel Consumption Comb (mpg)` | Combined fuel consumption in miles per gallon |
| `CO2 Emissions(g/km)` | CO₂ emissions in grams per kilometre |

### Practice Goal

By completing the questions below, you will practice the same beginner-level Pandas concepts covered earlier, including:

`read_csv()`, `head()`, `tail()`, `shape`, `columns`, `dtypes`, `info()`, `isnull()`, `isna()`, `sum()`, column selection, slicing, `loc`, `iloc`, `unique()`, `nunique()`, `value_counts()`, `max()`, filtering, `query()`, string methods, `apply()`, `lambda`, creating columns, `drop()`, `rename()`, `select_dtypes()`, `to_numpy()` and `to_csv()`.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **CO2 Emissions_Canada.csv** into a DataFrame named `df`.

In [1]:
import pandas as pd
path = r"D:\liha tech\Data-Science-Assignments-main\Assignment 0.1\CO2 Emissions_Canada.csv"
df = pd.read_csv(path)
df.head(2)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221

### Question 2
Display the first **5 rows** of the dataset.

In [2]:
df.head(5)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

### Question 3
Display the last **5 rows** of the dataset.

In [3]:
df.tail(5)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

### Question 4
Find the total number of **rows and columns** in the dataset.

In [4]:
df.shape

(7385, 12)

### Question 5
Display all the **column names** present in the dataset.

In [5]:
df.columns

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'],
      dtype='object')

### Question 6
Display the **data type of each column**.

In [6]:
df.dtypes

Make                                 object
Model                                object
Vehicle Class                        object
Engine Size(L)                      float64
Cylinders                             int64
Transmission                         object
Fuel Type                            object
Fuel Consumption City (L/100 km)    float64
Fuel Consumption Hwy (L/100 km)     float64
Fuel Consumption Comb (L/100 km)    float64
Fuel Consumption Comb (mpg)           int64
CO2 Emissions(g/km)                   int64
dtype: object

### Question 7
Display a complete summary of the DataFrame using `info()`.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7385 entries, 0 to 7384
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Make                              7385 non-null   object
 1   Model                             7385 non-null   object
 2   Vehicle Class                     7385 non-null   object
 3   Engine Size(L)                    7385 non-null   float64
 4   Cylinders                         7385 non-null   int64
 5   Transmission                      7385 non-null   object
 6   Fuel Type                         7385 non-null   object
 7   Fuel Consumption City (L/100 km)  7385 non-null   float64
 8   Fuel Consumption Hwy (L/100 km)   7385 non-null   float64
 9   Fuel Consumption Comb (L/100 km)  7385 non-null   float64
 10  Fuel Consumption Comb (mpg)       7385 non-null   int64
 11  CO2 Emissions(g/km)               7385 non-null   int64
dtypes: float64(4), int64(3), object(5)
memory usage: 692.5+ KB

## 2. Checking Missing Values

### Question 8
Check the number of **null values in each column** using `isnull()`.

In [8]:
df.isnull().sum()

Make                                0
Model                               0
Vehicle Class                       0
Engine Size(L)                      0
Cylinders                           0
Transmission                        0
Fuel Type                           0
Fuel Consumption City (L/100 km)    0
Fuel Consumption Hwy (L/100 km)     0
Fuel Consumption Comb (L/100 km)    0
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
dtype: int64

### Question 9
Check the number of missing values again using `isna()`.

In [9]:
df.isna().sum()

Make                                0
Model                               0
Vehicle Class                       0
Engine Size(L)                      0
Cylinders                           0
Transmission                        0
Fuel Type                           0
Fuel Consumption City (L/100 km)    0
Fuel Consumption Hwy (L/100 km)     0
Fuel Consumption Comb (L/100 km)    0
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
dtype: int64

## 3. Selecting Data

### Question 10
Select and display only the **Make** column.

In [10]:
df['Make']

0       ACURA
1       ACURA
2       ACURA
3       ACURA
4       ACURA
        ...
7380    VOLVO
7381    VOLVO
7382    VOLVO
7383    VOLVO
7384    VOLVO
Name: Make, Length: 7385, dtype: object

### Question 11
Select and display the **Make, Model, and CO2 Emissions(g/km)** columns.

In [11]:
df[['Make','Model','CO2 Emissions(g/km)']]

       Make        Model  CO2 Emissions(g/km)
0     ACURA          ILX                  196
1     ACURA          ILX                  221
2     ACURA   ILX HYBRID                  136
3     ACURA      MDX 4WD                  255
4     ACURA      RDX AWD                  244
...     ...          ...                  ...
7380  VOLVO  XC40 T5 AWD                  219
7381  VOLVO  XC60 T5 AWD                  232
7382  VOLVO  XC60 T6 AWD                  240
7383  VOLVO  XC90 T5 AWD                  232
7384  VOLVO  XC90 T6 AWD                  248

[7385 rows x 3 columns]

### Question 12
Display the first **10 rows** using DataFrame slicing.

In [12]:
df[:10]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
5,ACURA,RLX,MID-SIZE,3.5,6,AS6,Z,11.9,7.7,10.0,28,230
6,ACURA,TL,MID-SIZE,3.5,6,AS6,Z,11.8,8.1,10.1,28,232
7,ACURA,TL AWD,MID-SIZE,3.7,6,AS6,Z,12.8,9.0,11.1,25,255
8,ACURA,TL AWD,MID-SIZE,3.7,6,M6,Z,13.4,9.5,11.6,24,267
9,ACURA,TSX,COMPACT,2.4,4,AS5,Z,10.6,7.5,9.2,31,212

### Question 13
Using `iloc`, display the first **5 rows and first 4 columns**.

In [13]:
df.iloc[:5,:4]

    Make       Model Vehicle Class  Engine Size(L)
0  ACURA         ILX       COMPACT             2.0
1  ACURA         ILX       COMPACT             2.4
2  ACURA  ILX HYBRID       COMPACT             1.5
3  ACURA     MDX 4WD   SUV - SMALL             3.5
4  ACURA     RDX AWD   SUV - SMALL             3.5

### Question 14
Using `loc`, display rows **0 to 4** for the columns **Make, Model, and Cylinders**.

In [14]:
df.loc[:4,['Make','Model','Cylinders']]

    Make       Model  Cylinders
0  ACURA         ILX          4
1  ACURA         ILX          4
2  ACURA  ILX HYBRID          4
3  ACURA     MDX 4WD          6
4  ACURA     RDX AWD          6

## 4. Exploring Unique Values

### Question 15
Display all the **unique vehicle manufacturers (Make)** in the dataset.

In [15]:
df['Make'].unique()

array(['ACURA', 'ALFA ROMEO', 'ASTON MARTIN', 'AUDI', 'BENTLEY', 'BMW',
       'BUICK', 'CADILLAC', 'CHEVROLET', 'CHRYSLER', 'DODGE', 'FIAT',
       'FORD', 'GMC', 'HONDA', 'HYUNDAI', 'INFINITI', 'JAGUAR', 'JEEP',
       'KIA', 'LAMBORGHINI', 'LAND ROVER', 'LEXUS', 'LINCOLN', 'MASERATI',
       'MAZDA', 'MERCEDES-BENZ', 'MINI', 'MITSUBISHI', 'NISSAN',
       'PORSCHE', 'RAM', 'ROLLS-ROYCE', 'SCION', 'SMART', 'SRT', 'SUBARU',
       'TOYOTA', 'VOLKSWAGEN', 'VOLVO', 'GENESIS', 'BUGATTI'],
      dtype=object)

### Question 16
Find the total number of **unique vehicle manufacturers**.

In [17]:
df['Make'].nunique()

42

### Question 17
Display all unique values from the **Fuel Type** column.

In [18]:
df['Fuel Type'].unique()

array(['Z', 'D', 'X', 'E', 'N'], dtype=object)

### Question 18
Count how many records belong to each **Make** using `value_counts()`.

In [19]:
df['Make'].value_counts()

Make
FORD             628
CHEVROLET        588
BMW              527
MERCEDES-BENZ    419
PORSCHE          376
TOYOTA           330
GMC              328
AUDI             286
NISSAN           259
JEEP             251
DODGE            246
KIA              231
HONDA            214
HYUNDAI          210
MINI             204
VOLKSWAGEN       197
MAZDA            180
LEXUS            178
JAGUAR           160
CADILLAC         158
SUBARU           140
VOLVO            124
INFINITI         108
BUICK            103
RAM               97
LINCOLN           96
MITSUBISHI        95
CHRYSLER          88
LAND ROVER        85
FIAT              73
ACURA             72
MASERATI          61
ROLLS-ROYCE       50
ASTON MARTIN      47
BENTLEY           46
LAMBORGHINI       41
ALFA ROMEO        30
GENESIS           25
SCION             22
SMART              7
BUGATTI            3
SRT                2
Name: count, dtype: int64

### Question 19
Count how many vehicles belong to each **Vehicle Class**.

In [20]:
df['Vehicle Class'].value_counts()

Vehicle Class
SUV - SMALL                 1217
MID-SIZE                    1133
COMPACT                     1022
SUV - STANDARD               735
FULL-SIZE                    639
SUBCOMPACT                   606
PICKUP TRUCK - STANDARD      538
TWO-SEATER                   460
MINICOMPACT                  326
STATION WAGON - SMALL        252
PICKUP TRUCK - SMALL         159
MINIVAN                       80
SPECIAL PURPOSE VEHICLE       77
VAN - PASSENGER               66
STATION WAGON - MID-SIZE      53
VAN - CARGO                   22
Name: count, dtype: int64

## 5. Basic Analysis and Filtering

### Question 20
Find the **maximum CO₂ emission value** available in the dataset.

### Question 21
Display all vehicles whose **CO2 Emissions(g/km) are greater than 300**.

### Question 22
Display all vehicles whose **Engine Size(L) is greater than 4.0**.

### Question 23
Display only the vehicles manufactured by **BMW**.

### Question 24
Using `query()`, display all vehicles having **8 cylinders**.

### Question 25
Display vehicles that have **CO₂ emissions greater than 250** and **Cylinders equal to 8**.

## 6. Simple String Operations

### Question 26
Display all vehicle models whose **Model name starts with the letter `C`**.

### Question 27
Convert the values in the **Make** column to uppercase using a Pandas string method and display the result.

## 7. Creating and Modifying Columns

### Question 28
Create a new column called **Emission Level**. Store `High` when `CO2 Emissions(g/km)` is greater than 250; otherwise store `Normal`. Use `apply()` with a `lambda` function.

### Question 29
Display the first **10 rows** after creating the **Emission Level** column.

### Question 30
Remove the **Emission Level** column using `drop()`.

### Question 31
Rename the column **CO2 Emissions(g/km)** to **CO2_Emissions**.

## 8. Conversion and Export

### Question 32
Select and display only the **numeric columns** from the dataset using `select_dtypes()`.

### Question 33
Convert the first **10 rows** of the DataFrame into a NumPy array using `to_numpy()`.

### Question 34
Replace spaces in all column names with underscores using `columns.str.replace()`.

### Question 35
Save the DataFrame as a new CSV file named **CO2_Emissions_Practice_Output.csv** using `to_csv()` without saving the index.

## End of Practice

Try to solve each question independently.  
The main goal is to become comfortable with **basic Pandas syntax and DataFrame operations** before moving to more advanced EDA topics such as grouping, aggregation, pivot tables, correlation, and visualization.